---
pull_request_rules:
  - name: automatic merge when CI passes and 2 reviews
    conditions:
      - status-success=continuous-integration/travis-ci
      - base=master
    actions:
      merge:
        method: merge
