---
dist: xenial
sudo: required
language: python
env:
  matrix:
    - LXD_DISTRO: debian/stretch/amd64
    - LXD_DISTRO: ubuntu/bionic/amd64
    - LXD_DISTRO: ubuntu/xenial/amd64
cache:
  pip: true
before_install:
  - sudo apt-get -qq update
  - sudo apt install -t xenial-backports
  - sudo apt install -y lxd lxd-client python-dev libffi-dev libssl-dev openssl
  - sudo lxd init --auto;
  - sudo usermod -a -G lxd travis
install:
  - sudo pip install -U pip
  - sudo pip uninstall -y pyOpenSSL
  - sudo pip install -U cryptography==2.6.1
  - sudo pip install --ignore-installed PyYAML
  - sudo pip install molecule==2.19.0
script:
  - sudo molecule --debug test
