---
dependency:
  name: galaxy
driver:
  name: lxd
lint:
  name: yamllint
platforms:
  - name: xenial-gitea
    alias: ubuntu/xenial/amd64
  - name: bionic-gitea
    alias: ubuntu/bionic/amd64
  - name: jessie-gitea
    alias: debian/jessie/amd64
  - name: stretch-gitea
    alias: debian/stretch/amd64
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
